
import PlaceHolder.PlaceHolder;
import java.applet.AudioClip;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.poi.hssf.util.HSSFColor;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jona
 */
public class CambiarAlarma_Producto extends javax.swing.JFrame {

    /**
     * Creates new form CambiarAlarma_Producto
     */
    public CambiarAlarma_Producto() {
        initComponents();
 Texto_codigo.requestFocus();//esto es para que se puede volver a escribir en el Jtext si tener que clickearlo
        try {//ESTO TIENE QUE VER CON LA CLASE FONDOSQING PARA COLOCAR IMAGEN DE FONDO
            FondoSwing fondo = new FondoSwing(ImageIO.read(new File("BD/Fondo.jpg")));

            JPanel panel = (JPanel) this.getContentPane();
            panel.setBorder(fondo);
        } catch (IOException ex) {

        }

        diseño_Botones();

     //   this.setBounds(0, 0, 1080, 620); //modifico el ancho y alto por defecti si se minimiza

         this.setResizable(false); //para que no modifiquen el ancho y no se agrande
        this.setLocationRelativeTo(this); // para que este en el centro de la pantalla

        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/IRIS.png"));//le coloco el icono a la aplicacion

        this.setIconImage(icono);

       // this.setExtendedState(Inicio.MAXIMIZED_BOTH); // para que inicie ocupando toda la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Texto_alarma = new javax.swing.JTextField();
        Texto_codigo = new javax.swing.JTextField();
        Boton_ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Texto_alarma.setFont(new java.awt.Font("Tempus Sans ITC", 3, 25)); // NOI18N
        Texto_alarma.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Texto_alarma.setCaretColor(new java.awt.Color(255, 0, 204));
        Texto_alarma.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Texto_alarma.setSelectionColor(new java.awt.Color(255, 51, 204));
        Texto_alarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Texto_alarmaActionPerformed(evt);
            }
        });

        Texto_codigo.setFont(new java.awt.Font("Tempus Sans ITC", 3, 25)); // NOI18N
        Texto_codigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Texto_codigo.setCaretColor(new java.awt.Color(255, 0, 204));
        Texto_codigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Texto_codigo.setSelectionColor(new java.awt.Color(255, 51, 204));
        Texto_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Texto_codigoActionPerformed(evt);
            }
        });

        Boton_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ok.png"))); // NOI18N
        Boton_ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_ok.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ok2.png"))); // NOI18N
        Boton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Texto_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(Boton_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Texto_alarma, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Texto_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(Texto_alarma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Boton_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Texto_alarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Texto_alarmaActionPerformed

    }//GEN-LAST:event_Texto_alarmaActionPerformed

    private void Texto_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Texto_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Texto_codigoActionPerformed

    private void Boton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_okActionPerformed
       boolean AlarmaNumero = true;
       int alarmaNueva=0;
        try {//verificare que la alarma sea un numero
             alarmaNueva = Integer.parseInt(Texto_alarma.getText());
        } catch (Exception e) {
            AlarmaNumero=false;
        }
        
        
        if("".equals(Texto_codigo.getText()) || "".equals(Texto_alarma.getText()))   {

 AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Advertencia.wav"));
            sonido.play();
            Icon icon = new ImageIcon(getClass().getResource("/Imagenes/advertencia.png")); //para poner icono al aviso
            JOptionPane.showMessageDialog(null, "<html><b>Pero hay un campo vacio¯\\_(ツ)_/¯</b>", "??¯\\(o_o)/¯??", JOptionPane.INFORMATION_MESSAGE, icon);
            Texto_alarma.requestFocus();//esto es para que se puede volver a escribir en el Jtext si tener que clickearlo
}   
        
        else if(AlarmaNumero==false){
        
         AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Advertencia.wav"));
            sonido.play();
            Icon icon = new ImageIcon(getClass().getResource("/Imagenes/advertencia.png")); //para poner icono al aviso
            JOptionPane.showMessageDialog(null, "<html><b>La debe ser un numero!!!✘✘✘</b>", "????¯\\(o_o)/¯????", JOptionPane.INFORMATION_MESSAGE, icon);
            Texto_alarma.requestFocus();//esto es para que se puede volver a escribir en el Jtext si tener que clickearlo
        }
        
        else if(alarmaNueva<0){
        AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Advertencia.wav"));
            sonido.play();
            Icon icon = new ImageIcon(getClass().getResource("/Imagenes/advertencia.png")); //para poner icono al aviso
            JOptionPane.showMessageDialog(null, "<html><b>La alarma no puede ser negativa!✘✘✘</b>", "????¯\\(o_o)/¯????", JOptionPane.INFORMATION_MESSAGE, icon);
            Texto_alarma.requestFocus();//esto es para que se puede volver a escribir en el Jtext si tener que clickearlo
        }
        
        else{
    cambiarAlarma();
    
    }
    }//GEN-LAST:event_Boton_okActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void cambiarAlarma(){
        try {
            
            int contadorFilas = 3; //el primer oodigo esta en la celda 4 abajo
            boolean estado = true;
int alarmaPersonalizadaProducto=0;
int inventario=0;
            FileInputStream file = new FileInputStream(new File("Cuentas e inventario IRIS.xlsx"));

            XSSFWorkbook wb = new XSSFWorkbook(file);
            XSSFSheet sheet = wb.getSheetAt(2);//con q hoja empezaremos, 3 del excel

            while (estado == true) {
                XSSFRow fila = sheet.getRow(contadorFilas);//el primer oodigo esta en la celda 4 abajo
                
                if (fila == null)//si la fila no es nula no entra y el contador de filas se incrementa, es decir mirara la sgte fila
                {
                estado = false;
                    try {

                        file.close();

                        FileOutputStream output = new FileOutputStream("Cuentas e inventario IRIS.xlsx"); //ruta donde se guardare el archivo
                        wb.write(output);
                        output.close();
                        AudioClip sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Advertencia.wav"));
                        sonido.play();
                        Icon icon = new ImageIcon(getClass().getResource("/Imagenes/advertencia.png")); //para poner icono al aviso
                        JOptionPane.showMessageDialog(null, "<html><b>No se encontro el codigo!!✘ ⊙△⊙</b> \n busca el nombre del producto en el excel y veras el codigo(˘︹˘)", "uh! ⊙﹏⊙", JOptionPane.INFORMATION_MESSAGE, icon);
 Texto_codigo.requestFocus();//esto es para que se puede volver a escribir en el Jtext si tener que clickearlo
                    } catch (Exception e) {
                        AudioClip sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Error.wav"));
                        sonido.play();
                        Icon icon = new ImageIcon(getClass().getResource("/Imagenes/error.png")); //para poner icono al aviso
                        JOptionPane.showMessageDialog(null, "<html><b>No se pudo guardar el excel, vuelve a intentarlo</b> o(╥﹏╥)o", "uh! ⊙△⊙", JOptionPane.INFORMATION_MESSAGE, icon);
                    }
                }
                if(estado==false){
                Texto_codigo.requestFocus();//esto es para que se puede volver a escribir en el Jtext si tener que clickearlo
           break;
                }
                
                
                XSSFCell celda = fila.getCell(0); //voy verificando en cada fila la primera celda si el codigo se repite
                if(Texto_codigo.getText().equals(celda.getStringCellValue()) && estado==true){
                 estado = false;//termino el ciclo
                  celda = fila.getCell(2); //la alarma esta en la celda 3
                     celda.setCellValue(Texto_alarma.getText());
                     
                      try {//guardo por q mas abajo modificare el color del invetario
                         file.close();

                        FileOutputStream output = new FileOutputStream("Cuentas e inventario IRIS.xlsx"); //ruta donde se guardare el archivo
                        wb.write(output);
                        output.close();


                    } catch (Exception e) {
                        
                         AudioClip sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Error.wav"));
                        sonido.play();
                        Icon icon = new ImageIcon(getClass().getResource("/Imagenes/error.png")); //para poner icono al aviso
                        JOptionPane.showMessageDialog(null, "<html><b>No se pudo guardar el excel, vuelve a intentarlo</b> o(╥﹏╥)o", "uh! ⊙△⊙", JOptionPane.INFORMATION_MESSAGE, icon);
                  break;
                    }
                     
                      
                         sheet = wb.getSheetAt(2);//voy a la hoja 3
            fila = sheet.getRow(contadorFilas);  
              celda = fila.getCell(2);//cojo la alarma personalizada del producto
           alarmaPersonalizadaProducto = Integer.parseInt(celda.getStringCellValue());// y se la asigno a la variable
          
            sheet = wb.getSheetAt(0);//voy a la hoja 1
            fila = sheet.getRow(contadorFilas);  
              celda = fila.getCell(3);//cojo el inventario
           inventario = Integer.parseInt(celda.getStringCellValue());// y se la asigno a la variable
           

//vere el inventario ya es menor o igual a la alarma
             
           if(alarmaPersonalizadaProducto>= inventario){//si el inventario es menor o igual a la alarma
         sheet = wb.getSheetAt(0);//me devuelvo a la hoja 1
            fila = sheet.getRow(contadorFilas);  //obtengo la posicion del producto
              celda = fila.getCell(3);//cojo la alarma personalizada del producto
         
          XSSFCellStyle style1 = wb.createCellStyle(); 
          style1.setFillForegroundColor(HSSFColor.RED.index);//y le pongo color rojo al inventario
          style1.setFillPattern(CellStyle.SOLID_FOREGROUND); 
                 celda.setCellStyle(style1);//y se lo asigno a la celda

           }
           
           else{//si no es que el inventario es mayor a la alarma asi que lo pongo a blanco
                    sheet = wb.getSheetAt(0);//me devuelvo a la hoja 1
            fila = sheet.getRow(contadorFilas);  //obtengo la posicion del producto
              celda = fila.getCell(3);//cojo la alarma personalizada del producto
           //esto es para que me elimine una celda especifica, eliminare la celda que esta en rojo y le reasigno el valor
               Row row = sheet.getRow(contadorFilas);//numero columna (abajo) 
                Cell celdaEliminar = row.getCell(3);//numero fila -> solo borrare lo de la celda 3
               row.removeCell(celdaEliminar);//la elimino
              
                celda = fila.createCell(3);//y en la posicion 2 el nombre

                    celda.setCellValue(Texto_alarma.getText());

           }
           
           
             try {
                         file.close();

                        FileOutputStream output = new FileOutputStream("Cuentas e inventario IRIS.xlsx"); //ruta donde se guardare el archivo
                        wb.write(output);
                        output.close();
AudioClip  sonido= java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Realizado.wav"));
        sonido.play();
                        Icon icon = new ImageIcon(getClass().getResource("/Imagenes/guardado.png")); //para poner icono al aviso
                        JOptionPane.showMessageDialog(null, "<html><b>Actualizado con exito c: ✔</b> ٩(•̮̮̃•̃)۶", "✔✔✔✔✔✔✔", JOptionPane.INFORMATION_MESSAGE, icon);
                 Texto_codigo.setText("");
                 Texto_alarma.setText("");
                       
                          Texto_codigo.requestFocus();//esto es para que se puede volver a escribir en el Jtext si tener que clickearlo
                    } catch (Exception e) {
                        
                         AudioClip sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Error.wav"));
                        sonido.play();
                        Icon icon = new ImageIcon(getClass().getResource("/Imagenes/error.png")); //para poner icono al aviso
                        JOptionPane.showMessageDialog(null, "<html><b>No se pudo guardar el excel, vuelve a intentarlo</b> o(╥﹏╥)o", "uh! ⊙△⊙", JOptionPane.INFORMATION_MESSAGE, icon);
                    }
                     
                }
                else{
                contadorFilas++; //le sumo uno para pasar a la siguiente fila
                }
            
            }   
            
        } catch (FileNotFoundException ex) {
         AudioClip  sonido= java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Error.wav"));
        sonido.play();
            Icon icon = new ImageIcon(getClass().getResource("/Imagenes/error.png")); //para poner icono al aviso
            JOptionPane.showMessageDialog(null, "<html><b>No se a encontrado el excel!! lo moviste?</b>(ง ͠° ͟ل͜ ͡°)ง", "uh! ⊙﹏⊙", JOptionPane.INFORMATION_MESSAGE, icon);

        } catch (IOException ex) {
        AudioClip  sonido= java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Error.wav"));
        sonido.play();
            Icon icon = new ImageIcon(getClass().getResource("/Imagenes/error.png")); //para poner icono al aviso
            JOptionPane.showMessageDialog(null, "<html><b>Error desconocido ●︿●  vuelve a intentarlo!</b>", "uh! ⊙﹏⊙", JOptionPane.INFORMATION_MESSAGE, icon);
        }
               

    
    }
    
    public void diseño_Botones (){

        
        Boton_ok.setOpaque(false);
        Boton_ok.setContentAreaFilled(false);
        Boton_ok.setBorderPainted(false);
        
  PlaceHolder placeholder = new PlaceHolder("Codigo producto", Texto_codigo);
  placeholder = new PlaceHolder("Nueva alarma", Texto_alarma);
   
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarAlarma_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarAlarma_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarAlarma_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarAlarma_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarAlarma_Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_ok;
    private javax.swing.JTextField Texto_alarma;
    private javax.swing.JTextField Texto_codigo;
    // End of variables declaration//GEN-END:variables
}
