
import PlaceHolder.PlaceHolder;
import java.applet.AudioClip;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.sourceforge.barbecue.Barcode;
import net.sourceforge.barbecue.BarcodeFactory;
import net.sourceforge.barbecue.BarcodeImageHandler;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jona
 */
public class GenerarCodigo extends javax.swing.JFrame {

    /**
     * Creates new form GenerarCodigo
     */
    public GenerarCodigo() {
        initComponents();
        Texto_codigo.requestFocus();//esto es para que se puede volver a escribir en el Jtext si tener que clickearlo
         try {//ESTO TIENE QUE VER CON LA CLASE FONDOSQING PARA COLOCAR IMAGEN DE FONDO
            FondoSwing fondo = new FondoSwing(ImageIO.read(new File("BD/Fondo.jpg")));

            JPanel panel = (JPanel) this.getContentPane();
            panel.setBorder(fondo);
        } catch (IOException ex) {
           
        }

        diseño_Botones();
        // diseño_Botones();//llama al metodo para que arregle todos los botones

        //this.setBounds(0, 0, 1080, 620); //modifico el ancho y alto por defecti si se minimiza

        // this.setResizable(false); //para que no modifiquen el ancho y no se agrande
        this.setLocationRelativeTo(GenerarCodigo.this); // para que este en el centro de la pantalla

        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/IRIS.png"));//le coloco el icono a la aplicacion

        this.setIconImage(icono);

       // this.setExtendedState(Inicio.MAXIMIZED_BOTH); // para que inicie ocupando toda la pantalla
       
        PlaceHolder placeholder = new PlaceHolder("Codigo item", Texto_codigo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Texto_codigo = new javax.swing.JTextField();
        Boton_copiar = new javax.swing.JButton();
        Boton_ok = new javax.swing.JButton();
        Label_codigo_barras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(374, 310));
        setResizable(false);
        setSize(new java.awt.Dimension(374, 310));

        Texto_codigo.setFont(new java.awt.Font("Tempus Sans ITC", 3, 30)); // NOI18N
        Texto_codigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Texto_codigo.setCaretColor(new java.awt.Color(255, 0, 204));
        Texto_codigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Texto_codigo.setSelectionColor(new java.awt.Color(255, 51, 204));
        Texto_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Texto_codigoActionPerformed(evt);
            }
        });

        Boton_copiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/copiar.png"))); // NOI18N
        Boton_copiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_copiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/copiar2.png"))); // NOI18N
        Boton_copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_copiarActionPerformed(evt);
            }
        });

        Boton_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ok.png"))); // NOI18N
        Boton_ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_ok.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ok2.png"))); // NOI18N
        Boton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Label_codigo_barras, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(Boton_copiar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(Texto_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(Boton_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_codigo_barras, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_copiar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Texto_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Boton_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void diseño_Botones(){
    Boton_ok.setOpaque(false);
        Boton_ok.setContentAreaFilled(false);
        Boton_ok.setBorderPainted(false);

        Boton_copiar.setOpaque(false);
        Boton_copiar.setContentAreaFilled(false);
        Boton_copiar.setBorderPainted(false);
        Boton_copiar.setVisible(false);
        
        
        
    }
    private void Texto_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Texto_codigoActionPerformed

    }//GEN-LAST:event_Texto_codigoActionPerformed

    private void Boton_copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_copiarActionPerformed
       
        Clipboard cb = Toolkit.getDefaultToolkit().getSystemClipboard();
        ImageIcon image = (ImageIcon) Label_codigo_barras.getIcon(); //PARA PODER COPIAR EL CODIGO
        ImageSelection dh = new ImageSelection(image.getImage());
        cb.setContents(dh, null);
        AudioClip  sonido2= java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Boton.wav"));
        sonido2.play();
        
        
    }//GEN-LAST:event_Boton_copiarActionPerformed

    private void Boton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_okActionPerformed

        
        if("".equals(Texto_codigo.getText())){
AudioClip  sonido= java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Advertencia.wav"));
        sonido.play();
            Icon icon = new ImageIcon(getClass().getResource("/Imagenes/advertencia.png")); //para poner icono al aviso
            JOptionPane.showMessageDialog(null, "<html><b>No has ingresado nada ¯\\_(ツ)_/¯</b>", " ¯\\(o_o)/¯", JOptionPane.INFORMATION_MESSAGE, icon);
Texto_codigo.requestFocus();//esto es para que se puede volver a escribir en el Jtext si tener que clickearlo
        }

        
else{

    String codigo_barras = Texto_codigo.getText();
        Barcode barcode = null;
        try {

            barcode = BarcodeFactory.createCode128(codigo_barras);//le asigno el codigo pa q genere las barras

            barcode.setBarWidth(2);//largo de las  barras
            barcode.setBarHeight(60); //ancho de las barras
            BufferedImage image = new BufferedImage(300, 100, BufferedImage.TYPE_INT_ARGB); // ,top
            Graphics2D g = (Graphics2D) image.getGraphics();

            barcode.draw(g, 5, 20);

            ImageIcon icon = new ImageIcon(image);
            FileOutputStream fos = new FileOutputStream("BD/BD/codigo.png");
            BarcodeImageHandler.writePNG(barcode, fos);
            rsscalelabel.RSScaleLabel.setScaleLabel(Label_codigo_barras, "BD/BD/codigo.png");
  
            AudioClip  sonido= java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Realizado.wav"));
        sonido.play();
            
Texto_codigo.setText("");
Texto_codigo.requestFocus();//esto es para que se puede volver a escribir en el Jtext si tener que clickearlo
            Boton_copiar.setVisible(true);
            

           
        } catch (FileNotFoundException ex) {
          AudioClip  sonido= java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Error.wav"));
        sonido.play();
            Icon icon = new ImageIcon(getClass().getResource("/Imagenes/error.png")); //para poner icono al aviso
            JOptionPane.showMessageDialog(null, "<html><b>No se encontro la imagen del codigo!! </b>⊙﹏⊙", "uh! ⊙﹏⊙", JOptionPane.INFORMATION_MESSAGE, icon);

        } catch (Exception z) {
            AudioClip  sonido= java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Error.wav"));
        sonido.play();
            Icon icon = new ImageIcon(getClass().getResource("/Imagenes/error.png")); //para poner icono al aviso
            JOptionPane.showMessageDialog(null, "<html><b>Error desconocido ●︿● vuelve a intentarlo!</b>", "uh! ⊙﹏⊙", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    
}
    }//GEN-LAST:event_Boton_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerarCodigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_copiar;
    private javax.swing.JButton Boton_ok;
    private javax.swing.JLabel Label_codigo_barras;
    private javax.swing.JTextField Texto_codigo;
    // End of variables declaration//GEN-END:variables
}
